2024-01-24 10:08:14,198:ERROR:{'message': "name 'a' is not defined", 'detail': 'Traceback (most recent call last):\n  File "C:\\Code\\codigofacilito-python\\Modulo 2 - Logs de Errores\\Context Manager\\main.py", line 15, in write_on_log_error\n    yield\n  File "C:\\Code\\codigofacilito-python\\Modulo 2 - Logs de Errores\\Context Manager\\main.py", line 26, in <module>\n    result = a + b\n             ^\nNameError: name \'a\' is not defined\n'}
2024-01-24 10:08:14,198:ERROR:{'message': "[Errno 2] No such file or directory: 'file.txt'", 'detail': 'Traceback (most recent call last):\n  File "C:\\Code\\codigofacilito-python\\Modulo 2 - Logs de Errores\\Context Manager\\main.py", line 15, in write_on_log_error\n    yield\n  File "C:\\Code\\codigofacilito-python\\Modulo 2 - Logs de Errores\\Context Manager\\main.py", line 31, in <module>\n    file = open("file.txt")\n           ^^^^^^^^^^^^^^^^\nFileNotFoundError: [Errno 2] No such file or directory: \'file.txt\'\n'}
